[project]
name = "licht"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "m-taqii", email = "busy.digital.master@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi[standard]>=0.141.1",
    "openai-agents>=0.22.3",
    "psycopg[binary]>=3.3.6",
    "pydantic-settings>=2.15.0",
    "resend>=2.47.0",
    "sqlalchemy>=2.0.54",
]

[project.scripts]
licht = "licht:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
